### ISSUE TITLE
Lzop Codec in Apache Spark

### ISSUE THREAD

**Issue by srinicodeit** [airlift/aircompressor#131]
Is there any documentation to use LzopCodec codec  in apache-spark ?

**Comment by dain** [comment]
You will need to create a subclass of the codec using the actual name hadoop used for the codec, because Hadoop, unfortunately, encodes the class name into the file formats.  Here is how we did this in a Trino test:
https://github.com/trinodb/trino/blob/master/lib/trino-hive-formats/src/test/java/com/hadoop/compression/lzo/LzopCodec.java#L18
