### ISSUE TITLE
The result is different

### ISSUE THREAD

**Issue by GoodbyeV** [airlift/aircompressor#175]
Why is my data compressed in java different from the data compressed by the lzo library implemented by ANSI C using jni on the mobile side

**Comment by dain** [comment]
Due to licensing differences, the LZO implementation in aircompressor is completely different from the C codebase.  The LZO implementation here is a version of the LZ4 codebase modified to output LZO commands instead of LZ4.  We do not recommend that people use LZO as it is an old algorithm, and LZ4 is better in every measurable way, and has a much better license.  We only provide LZO here as a way for people to migrate away from it.
